baseURL: "https://matthewcrews.com"
title: "Matthew Crews"
author: Matthew Crews
theme: "hugo-PaperMod"
menu:
  main:
    - name: About
      url: about

params:
  ShowShareButtons: true

  homeInfoParams:
    Title: F# + Mathematical Planning
    Content: I focus on the intersection of Mathematical Planning and Predictive Modeling.
      This blog is an exploration of applying these techniques to real world problems.
      Feel free to connect and ask questions. Enjoy!

  socialIcons: # optional
    - name: "email"
      url: "mailto:matthewcrews@gmail.com"
    - name: "twitter"
      url: "https://twitter.com/McCrews"
    - name: "github"
      url: "https://github.com/matthewcrews"
    - name: "rss"
      url: "https://matthewcrews.com/index.xml"